name: "Chore / Task"
description: "Non-feature maintenance work"
title: "[Chore] <short title>"
labels: ["chore"]
body:
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What needs doing?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How will we know this is done?