name: CI-CD
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  docker-build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        if: ${{ secrets.GHCR_PAT != '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=main,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=sha

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          push: ${{ secrets.GHCR_PAT != '' }}
          tags: ${{ steps.meta.outputs.tags }}
          context: .
          file: ./Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
