name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Verify environment (non-strict)
        continue-on-error: true
        run: node scripts/verify-env.mjs

      - name: Lint
        run: npm run lint --if-present

      - name: Test
        run: npm test --if-present -- --coverage

      - name: Typecheck (allowed to fail)
        continue-on-error: true
        run: npm run typecheck --if-present

      - name: Build (allowed to fail)
        continue-on-error: true
        run: npm run build --if-present

      - name: Upload coverage artifact (if present)
        if: ${{ hashFiles('coverage/lcov.info') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
