name: Weekly Security Audit

on:
  schedule:
    - cron: "0 8 * * 1" # Every Monday 08:00 UTC
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  npm-audit:
    name: npm audit
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run npm audit (non-blocking)
        id: audit
        run: |
          set -e
          NODE_OPTIONS="" npm audit --json > audit.json || true
          echo "report_path=audit.json" >> "$GITHUB_OUTPUT"
      - name: Upload audit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: ${{ steps.audit.outputs.report_path }}
